name: Deploy

on:
  push: {}
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    uses: Katsute/Workflows/.github/workflows/npm.electron.deploy.yml@main
    with: 
      token: ${{ secrets.GITHUB_TOKEN }}