name: npm CI

on:
  push: {}
  pull_request:
    branches: [main]

jobs:
  npm_ci:
    name: npm CI
    uses: Katsute/Workflows/.github/workflows/npm.ci.yml@main
    with:
      os: windows-latest # required for process-list rebuild
      timeout: 10
      rebuild: true
      test: false