name: npm CI
on:
  push: {}
  pull_request:
    branches: [main]
permissions: read-all

jobs:
  npm_ci:
    name: npm CI
    runs-on: windows-latest
    steps:
      - name: 📤 Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: 📚 Install npm
        uses: actions/setup-node@v2.3.2
        with:
          node-version: 14
          architecture: x64
          cache: npm

      - name: ✔ Compile with npm
        run: |
          npm ci

      - name: 🔄 Rebuild with Electron
        run: |
          npm run rebuild