name: npm CI
on:
  push: {}
  pull_request:
    branches: [main]

jobs:
  npm_ci:
    name: npm CI
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: 📤 Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: 📚 Install npm
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14
          architecture: x64
          cache: npm

      - name: ✔ Compile with npm
        run: |
          npm ci

      - name: 🔄 Rebuild with Electron
        run: |
          npm run rebuild

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: 📤 Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: 📚 Install CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: 📚 Install npm
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14
          architecture: x64
          cache: npm

      - name: ✔ Compile with npm
        run:
          npm ci

      - name: ✔ Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1